task:
  name: clang-format

  only_if: $CIRRUS_BASE_BRANCH == "main" || $CIRRUS_BRANCH == "main"

  container:
    image: rsmmr/clang:9.0

  test_script:
    - clang-format -version
    - 'git ls-files {Jucer2CMake/src,cmake/tools}/"*."{cpp,h,hpp}
      | xargs -d\\n clang-format -i -style=file -verbose'
    - git diff --exit-code
